controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    rrbot_controllers:
      type: velocity_controllers/JointGroupVelocityController

    # For publishing joint states from Gazebo to ROS
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


rrbot_controllers:
  ros__parameters:
    joints:
      - joint1
      - joint2
