/robot1/controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot1_controllers:
      type: velocity_controllers/JointGroupVelocityController

/robot1/robot1_controllers:
  ros__parameters:
    joints:
      - robot1/joint_1
      - robot1/joint_2
      - robot1/joint_3
      - robot1/joint_4
      - robot1/joint_5
      - robot1/joint_6

