/robot2/controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot2_controllers:
      type: velocity_controllers/JointGroupVelocityController

/robot2/robot2_controllers:
  ros__parameters:
    joints:
      - robot2/joint_1
      - robot2/joint_2
      - robot2/joint_3
      - robot2/joint_4
      - robot2/joint_5
      - robot2/joint_6

